# Default values for sgroups-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

sgroupsApiVersion: v1

server:
  enabled: true
  # This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
  replicaCount: 1

  # This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
  image:
    repository: prorobotech/sgroups.server
    # This sets the pull policy for images.
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  # This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  imagePullSecrets: []

  env: {}

  # This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Automatically mount a ServiceAccount's API credentials?
    automount: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  # This is for setting Kubernetes Annotations to a Pod.
  # For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  podAnnotations: {}
  # This is for setting Kubernetes Labels to a Pod.
  # For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
  podLabels: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    privileged: false
    readOnlyRootFilesystem: true
    runAsGroup: 65532
    runAsNonRoot: true
    runAsUser: 65532

  # This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
  service:
    # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
    type: LoadBalancer
    # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
    ports:
      server: 9008
      rbacproxy: 9006

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      ephemeral-storage: 50Mi
      memory: 64Mi

  # This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
  livenessProbe: {}
  readinessProbe: {}

  # This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  # Additional volumes on the output Deployment definition.
  volumes: []
  # - name: foo
  #   secret:
  #     secretName: mysecret
  #     optional: false

  # Additional volumeMounts on the output Deployment definition.
  volumeMounts: []
  # - name: foo
  #   mountPath: "/etc/foo"
  #   readOnly: true

  nodeSelector: {}
  
  tolerations:
    - key: node-role.kubernetes.io/data-plane
      effect: NoSchedule
    - key: node-role.kubernetes.io/in-cloud-infra
      effect: NoSchedule

  affinity: {}

  config:
    logger:
      level: DEBUG
    metrics:
      enable: true
    healthcheck:
      enable: true
    server:
      endpoint: tcp://0.0.0.0:9008
      graceful-shutdown: 30s
      # api-path-prefix: "apis/sgroups.io/v1"
    storage:
      type: postgres
    authn:
      type: none
      # tls:
      #   key-file: "/opt/h-bf/sgroups/tls/tls.key"
      #   cert-file: "/opt/h-bf/sgroups/tls/tls.crt"
      #   client:
      #     verify: skip
      #     ca-files:
      #       - "/opt/h-bf/sgroups/tls/ca.crt"

  rbacproxy:
    enabled: true
    # This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
    image:
      repository: gcr.io/kubebuilder/kube-rbac-proxy
      # This sets the pull policy for images.
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: "v0.16.0"

    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 65532
      runAsNonRoot: true
      runAsUser: 65532

    resources:
      requests:
        memory: 32Mi
        cpu: 10m
      limits:
        memory: 64Mi
        cpu: 50m

  migrationContainer:
    # This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
    image:
      repository: prorobotech/sgroups.goose
      # This sets the pull policy for images.
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: ""

    command:
      - /app/bin/goose
      - -table=sgroups_db_ver
      - postgres
      - $(SG_STORAGE_POSTGRES_URL)
      - up

    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 65532
      runAsNonRoot: true
      runAsUser: 65532

    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        ephemeral-storage: 50Mi
        memory: 128Mi

web:
  enabled: true
  # This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
  replicaCount: 1

  # This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
  image:
    repository: sgroups/sgroups.ui
    # This sets the pull policy for images.
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: v4.1.6-a7f09504

  # This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  imagePullSecrets: []

  env:
    HBF_API: http://release-name.prorobotech.ru/server
    BASE_PREFIX: "client"
    GRAPH_ENABLED: "false"

  # This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Automatically mount a ServiceAccount's API credentials?
    automount: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  # This is for setting Kubernetes Annotations to a Pod.
  # For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  podAnnotations: {}
  # This is for setting Kubernetes Labels to a Pod.
  # For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
  podLabels: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext:
    allowPrivilegeEscalation: true
    privileged: true
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
    runAsNonRoot: false

  # This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
  service:
    # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
    type: ClusterIP
    # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
    ports:
      ingress: 80

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  # This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
  livenessProbe: {}
  readinessProbe: {}

  # This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  # Additional volumes on the output Deployment definition.
  volumes: []
  # - name: foo
  #   secret:
  #     secretName: mysecret
  #     optional: false

  # Additional volumeMounts on the output Deployment definition.
  volumeMounts: []
  # - name: foo
  #   mountPath: "/etc/foo"
  #   readOnly: true

  nodeSelector: {}
  
  tolerations:
    - key: node-role.kubernetes.io/data-plane
      effect: NoSchedule
    - key: node-role.kubernetes.io/in-cloud-infra
      effect: NoSchedule

  affinity: {}

# Database
externalDatabase:
  enabled: true
  url: postgresql
  port: 5432
  database: netguard
  username: netguard
  password: netguard
  sslmode: false

postgresql:
  enabled: false
  image:
    repository: bitnamilegacy/postgresql
  global:
    security:
      allowInsecureImages: true

# Certs for tls/mtls between services
internalTLS:
  # There are three ways to provide tls
  # 1) "certmanager" will generate cert automatically
  # 2) "secret" internal certificates from secret
  # 3) "none" no certificates
  certSource: none
  certmanager:
    # existingIssuer
    # if you want to use an existing issuer, you must specify:
    # kind (Issuer or ClusterIssuer) and name
    existingIssuer:
      kind: Issuer
      name: ""
    extraDnsNames: []
    extraIPAddresses: []
  secret:
    # Each name of secret must contain keys named:
    # "tls.crt" - the certificate
    # "tls.key" - the private key

    # server related cert configuration
    server:
      # secret name for server's tls certs
      secretName: ""

externalDomain: "sgroups.example.com"
expose:
  enabled: false
  # resourceType: allowed values [istio, ingress]
  resourceType: ingress

  ingress:
    annotations: {}
    labels: {}
    ingressClassName: ""

  istio:
    gateway:
      enabled: true
      name: incloud-istio-gateway
      istioLabelsSelector: {} # required value!
        # istio: istio-ingressgateway
      annotations: {}
      labels: {}
    virtualService:
      annotations: {}
      labels: {}

  # The path should end with a "/"
  path: /

  tls:
    # The source of the tls certificate. Set as "certmanager", "secret"
    # or "none" and fill the information in the corresponding section
    # 1) certmanager: generate the tls certificate automatically over CertManager
    # 2) secret: read the tls certificate from the specified secret.
    # The tls certificate can be generated manually or by cert manager
    # 3) none: configure no tls certificate for the ingress. If the default
    # tls certificate is configured in the ingress controller, choose this option
    certSource: none
    certmanager:
      # existingIssuer
      # if you want to use an existing issuer, you must specify:
      # kind (Issuer or ClusterIssuer) and name
      existingIssuer:
        kind: Issuer
        name: ""
    secret:
      # The name of secret which contains keys named:
      # "tls.crt" - the certificate
      # "tls.key" - the private key
      secretName: ""
