{{- $web    := .Values.web -}}
{{- $sa     := $web.serviceAccount -}}
{{- $saName := default (printf "%s-web" (include "sgroups-chart.fullname" .)) $sa.name -}}
{{- if not $sa.create }}
{{- $saName = "default" -}}
{{- end }}

{{- if $web.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sgroups-chart.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: web
    {{- include "sgroups-chart.labels" . | nindent 4 }}
spec:
  {{- if not $web.autoscaling.enabled }}
  replicas: {{ $web.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sgroups-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with $web.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: web
        {{- include "sgroups-chart.labels" . | nindent 8 }}
        {{- with $web.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with $web.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ $saName }}
      {{- with $web.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: web
          {{- with $web.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ $web.image.repository }}:{{ $web.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ $web.image.pullPolicy }}
          command:
            - /bin/bash
            - -c
            - /usr/share/nginx/html/client/env.sh && exec nginx -g 'daemon off;'
          {{- with $web.env }}
          env:
            {{ range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          ports:
            - name: ingress
              containerPort: {{ $web.service.ports.ingress }}
              protocol: TCP
          {{- with $web.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $web.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $web.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $web.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with $web.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $web.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $web.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
