{{- $web := .Values.web -}}
{{- if $web.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sgroups-chart.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: web
    {{- include "sgroups-chart.labels" . | nindent 4 }}
spec:
  type: {{ $web.service.type }}
  ports:
    - port: {{ $web.service.ports.ingress }}
      targetPort: ingress
      protocol: TCP
      name: ingress
  selector:
    app.kubernetes.io/component: web
    {{- include "sgroups-chart.selectorLabels" . | nindent 4 }}
{{- end }}
