{{- $server       := .Values.server -}}
{{- $config       := $server.config | default dict -}}
{{- $authnConfig  := $config.authn | default dict -}}
{{- $certFile     := (dig "tls" "cert-file" "/opt/h-bf/sgroups/tls/tls.crt" $authnConfig) -}}
{{- $keyFile      := (dig "tls" "key-file" "/opt/h-bf/sgroups/tls/tls.key" $authnConfig) -}}
{{- $clientCa     := (dig "tls" "client" "ca-files" (list "/opt/h-bf/sgroups/tls/ca.crt") $authnConfig) -}}
{{- $clientVerify := (dig "tls" "client" "verify" "skip" $authnConfig) -}}

{{- if $server.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sgroups-chart.fullname" . }}-server-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: server
    {{- include "sgroups-chart.labels" . | nindent 4 }}
data:
  config: |
    logger:
      {{- $config.logger | toYaml | nindent 6 }}
    metrics:
      {{- $config.metrics | toYaml | nindent 6 }}
    healthcheck:
      {{- $config.healthcheck | toYaml | nindent 6 }}
    server:
      endpoint: tcp://0.0.0.0:{{ $server.service.ports.server.port }}
    storage:
      {{- $config.storage | toYaml | nindent 6 }}
    authn:
    {{- if or (eq .Values.internalTLS.certSource "none") (eq $authnConfig.type "none") }}
      type: "none"
      tls:
        client:
          verify: "skip"
    {{- else }}
      type: "tls"
      tls:
        cert-file: {{ $certFile }}
        key-file: {{ $keyFile }}
        client:
          verify: {{ $clientVerify }}
          ca-files: {{ $clientCa | toYaml }}
    {{- end }}
{{- end }}
