{{- $server := .Values.server -}}
{{- if $server.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sgroups-chart.fullname" . }}-server
  labels:
    app.kubernetes.io/component: server
    {{- include "sgroups-chart.labels" . | nindent 4 }}
spec:
  type: {{ $server.service.type }}
  ports:
    - port: {{ $server.service.ports.server }}
      targetPort: server
      protocol: TCP
      name: server
    {{- if $server.rbacproxy.enabled }}
    - port: {{ $server.service.ports.ingress }}
      targetPort: ingress
      protocol: TCP
      name: ingress
    {{- end }}
  selector:
    app.kubernetes.io/component: server
    {{- include "sgroups-chart.selectorLabels" . | nindent 4 }}
{{- end }}
