{{- $server  := .Values.server -}}
{{- $sa       := $server.serviceAccount -}}
{{- $saName   := default (printf "%s-server" (include "sgroups-chart.fullname" .)) $sa.name -}}

{{- if and $server.enabled $sa.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $saName }}
  labels:
    app.kubernetes.io/component: server
    {{- include "sgroups-chart.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
