{{- $server := .Values.server -}}
{{- if $server.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sgroups-chart.fullname" . }}-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: server
    {{- include "sgroups-chart.labels" . | nindent 4 }}
spec:
  type: {{ $server.service.type }}
  ports:
    {{- with $server.service.ports.server }}
    - port: {{ .port }}
      targetPort: server
      protocol: TCP
      name: server
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
    {{- if $server.rbacproxy.enabled }}
    {{- with $server.service.ports.rbacproxy }}
    - port: {{ .port }}
      targetPort: rbacproxy
      protocol: TCP
      name: rbacproxy
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
    {{- end }}
  selector:
    app.kubernetes.io/component: server
    {{- include "sgroups-chart.selectorLabels" . | nindent 4 }}
{{- end }}
